In [1]:
array = np.zeros(10)

NameError: name 'np' is not defined

In [2]:
new_array = np.zeros(10)

NameError: name 'np' is not defined

In [3]:
pip install numpy


     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ------------ ------------------------- 20.5/61.0 kB 682.7 kB/s eta 0:00:01
     ------------------------------- ------ 51.2/61.0 kB 525.1 kB/s eta 0:00:01
     -------------------------------------- 61.0/61.0 kB 540.4 kB/s eta 0:00:00
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB 1.3 MB/s eta 0:00:13
   ---------------------------------------- 0.1/15.8 MB 1.1 MB/s eta 0:00:15
   ---------------------------------------- 0.2/15.8 MB 1.1 MB/s eta 0:00:14
    --------------------------------------- 0.2/15.8 MB 1.3 MB/s eta 0:00:13
    --------------------------------------- 0.3/15.8 MB 1.4 MB/s eta 0:00:12
    --------------------------------------- 0.4/15.8 MB 1.3 MB/s eta 0:00:12
   - -------------------------------------- 0.4/15.8 MB 1.4 MB/s eta 0:00:12
   - -------------------------------------- 0.5/15.8 MB 1.4 MB/s eta 0:00:11
  

ERROR: Could not install packages due to an OSError: [WinError 2] The system cannot find the file specified: 'C:\\Python310\\Scripts\\f2py.exe' -> 'C:\\Python310\\Scripts\\f2py.exe.deleteme'


[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import numpy as np


In [5]:
array = np.zeros(10)

In [6]:
array


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
array=np.random.rand(1,50)

In [8]:
array


array([[0.77748369, 0.35706959, 0.38203127, 0.51104885, 0.17410904,
        0.45148558, 0.91705784, 0.93269506, 0.03241315, 0.01042506,
        0.4829118 , 0.68801309, 0.06069488, 0.05430468, 0.11136704,
        0.24979421, 0.93010662, 0.40100353, 0.55552878, 0.08064726,
        0.21127261, 0.6382485 , 0.56671886, 0.39474112, 0.54112029,
        0.72718196, 0.06628402, 0.29308026, 0.10213956, 0.01451394,
        0.88129534, 0.40909749, 0.83978416, 0.86602269, 0.1980675 ,
        0.27576289, 0.21521862, 0.25223994, 0.17326017, 0.32587291,
        0.36639872, 0.78883148, 0.25418667, 0.68414181, 0.91984311,
        0.9552802 , 0.21158401, 0.33348006, 0.10319737, 0.5108983 ]])

In [9]:
array=np.random.randint(1, 50, size=(10))

In [10]:
array

array([17, 29, 23, 24, 47,  4, 42, 28, 30, 11])

In [11]:
np.mean(array)

25.5

In [12]:
arr1=np.zero(3,3_

SyntaxError: invalid decimal literal (2272611331.py, line 1)

In [13]:
arr1=np.zero(3,3)

AttributeError: module 'numpy' has no attribute 'zero'

In [14]:
arr1 = np.array([[1, 2, 3], [4, 5, 6], [5, 6, 7]])


In [15]:
arr2 = np.array([[1, 2, 3], [4, 5, 6], [5, 6, 7]])


In [16]:
ab=arr1+arr2

In [17]:
ab

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [10, 12, 14]])

In [18]:
np.mean(ab)

8.666666666666666

In [19]:
array=np.random.randint(1, 100, size=(20))

In [20]:
array

array([11, 93, 38, 37, 15, 62,  2, 94, 20, 59, 91, 89, 91, 13, 50, 48, 11,
       57, 69, 18])

In [24]:
condition = array > 50
filtered_arr = array[condition]
filtered_arr

array([93, 62, 94, 59, 91, 89, 91, 57, 69])

In [ ]:
arr

In [25]:
arr1 = np.array[1, 2, 34, 5, 65, 6, 7]


TypeError: 'builtin_function_or_method' object is not subscriptable

In [26]:
arr1=np.array([1,2,3,4,5,6,7,8,9,10])

In [27]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
np.randon.shuffle(arr1)

AttributeError: module 'numpy' has no attribute 'randon'

In [29]:
np.random.shuffle(arr1)

In [30]:
arr1

array([ 1,  8,  9,  4,  2,  3,  6, 10,  5,  7])

In [34]:
rand=np.random.randint(1,1000)

In [35]:
rand

506

In [36]:
rand=np.random.randint()

TypeError: randint() takes at least 1 positional argument (0 given)

In [37]:
rand=np.random.rand()

In [38]:
rand

0.39084353862536503

In [41]:
rand=np.random.randint(1,10)

In [42]:
rand

2

In [43]:
condition =np.random.randint(1,10)
filtered_arr = array[condition]
filtered_arr

20